/**
 * Autogenerated base class for the Travel model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Travel.js file.
 *
 * @module Travel
 */
var Q = require('Q');
var Db = Q.require('Db');

/**
 * Base class for the Travel model
 * @namespace Base
 * @class Travel
 * @static
 */
function Base () {
	return this;
}
 
module.exports = Base;

/**
 * The list of model classes
 * @property tableClasses
 * @type array
 */
Base.tableClasses = [
	"Travel_Trip"
];

/**
 * This method calls Db.connect() using information stored in the configuration.
 * If this has already been called, then the same db object is returned.
 * @method db
 * @return {Db} The database connection
 */
Base.db = function () {
	return Db.connect('Travel');
};

/**
 * The connection name for the class
 * @method connectionName
 * @return {string} The name of the connection
 */
Base.connectionName = function() {
	return 'Travel';
};

/**
 * Link to Travel.Trip model
 * @property Trip
 * @type Travel.Trip
 */
Base.Trip = Q.require('Travel/Trip');
