<?php

/**
 * Autogenerated base class for the Travel model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Travel.php file.
 *
 * @module Travel
 */
/**
 * Base class for the Travel model
 * @class Base_Travel
 */
abstract class Base_Travel
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Travel_Trip',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Travel');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Travel';
	}
};